config/routes.rb
Rails.application.routes.draw do
	root 'billboards#index'
	resources :billboards do
		resources :artists
	end
	resources :artists do
		resources :songs
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	validates :name, presence: true
	validates :name, uniqueness: true
	belongs_to :billboard
	has_many :songs, dependent: :destroy
end

app/models/billboard.rb
class Billboard < ApplicationRecord
	validates :name, presence: true
	validates :name, uniqueness: true
	has_many :artists, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  validates :name, presence: true
  validates :genre, presence: true
  validates :length, presence: true

  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

	before_action :set_billboard
	before_action :set_artist, only: [ :show, :update, :edit, :destroy ]


  def index
  	@artists = @billboard.artists
  end

  def show
  	# before_action set_billboard to get the ID
  end

  def new
  	@artist = @billboard.artists.new
  	render partial: 'form'
  end

  def create
  	@artist = @billboard.artists.new(artist_params)
  	if @artist.save
  		redirect_to [@billboard, @artist]
  	else
  		render partial: 'form'
  	end
  end

  def edit
  	render partial: 'form'
  end

  def update
  	if @artist.update(artist_params)
  		redirect_to [@billboard, @artist]
  	else
  		render partial: 'form'
  	end
  end

  def destroy
  	@artist.destroy
  	redirect_to billboard_artists_path(@billboard)
  end

  private
  def set_billboard
  	@billboard = Billboard.find(params[:billboard_id])
  end

  def set_artist
  	@artist = Artist.find(params[:id])
  end

  def artist_params
  	params.require(:artist).permit(:name)
  end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController

	before_action :set_billboard, only: [:show, :edit, :update, :destroy]

  def index
  	@billboards = Billboard.all
  end

  def show
  	# before_action set_billboard to get the ID
  end

  def new
  	@billboard = Billboard.new
  	render partial: 'form'
  end

  def create
  	@billboard = Billboard.new(billboard_params)
  	if @billboard.save
  		redirect_to billboards_path
  	else
  		render partial: 'form'
  	end
  end

  def edit
  	# before_action set_billboard to get the ID
  	render partial: 'form'
  end

  def update
  	if @billboard.update(billboard_params)
  		redirect_to @billboard
  	else
  		render partial: 'form'
  	end
  end

  def destroy
  	@billboard.destroy
  	redirect_to root_path
  end

  def destroy
    @billboard.destroy 
    redirect_to root_path
  end


  private

  def billboard_params
  	params.require(:billboard).permit(:name)
  end

  def set_billboard
  	@billboard = Billboard.find(params[:id])
  end

  def billboard_params
    params.require(:billboard).permit(:name)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	before_action :set_artist
	before_action :set_song, only: [ :show, :update, :edit, :destroy ]

  def index
  	@songs = @artist.songs
  end

  def show
  	# before_action set_billboard to get the ID
  end

  def new
  	@song = @artist.songs.new
  	render partial: 'form'
  end

  def create
  	@song = @artist.songs.new(song_params)
  	if @song.save
  		redirect_to [@artist, @song]
  	else
  		render partial: 'form'
  	end
  end

  def edit
  	render partial: 'form'
  end

  def update
  	if @song.update(song_params)
  		redirect_to [@artist, @song]
  	else
  		render partial: 'form'
  	end
  end

  def destroy
  	@song.destroy
  	redirect_to artist_songs_path(@artist)
  end

  private
  def set_artist
  	@artist = Artist.find(params[:artist_id])
  end

  def set_song
  	@song = Song.find(params[:id])
  end

  def song_params
  	params.require(:song).permit(:name, :genre, :length)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Edit Artist' : 'Create Artist' %></h1>
<%= form_for [@billboard, @artist] do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, required: true %>
	<br />
	<%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists</h1>
<%= link_to 'Create Artist', new_billboard_artist_path(@billboard) %>
<ul>
	<% @artists.each do |artist| %>
		<li>
			<%= link_to artist.name, [@billboard, artist] %>
		</li>
	<% end %>
</ul>
<br />
<%= link_to "Back to #{@billboard.name}", billboard_path(@billboard) %>

app/views/artists/new.html.erb
<h1><%= @artist.name %></h1>
<h3><%= link_to "Back to the Billboard charts", root_path %></h3>
<hr />

<h2><%= link_to "Add a Song", new_artist_song_path(@billboard) %></h2>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= link_to 'View Songs', artist_songs_path(@artist) %>
<br />
<%= link_to 'Edit', edit_billboard_artist_path(@billboard) %>
<br />
<%= link_to 'Delete', [@billboard, @artist], method: :delete %>
<p><%= link_to 'Back to Artists', billboard_artists_path(@billboard) %></p>

app/views/billboards/_form.html.erb
<h1><%= @billboard.id ? 'Edit Billboard' : 'Create Billboard' %></h1>
<%= form_for @billboard do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, required: true %>
	<br />
	<%= f.submit %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1>Top Billboards!</h1>
<%= link_to 'Create a new billboard', new_billboard_path %>
<ul>
	<% @billboards.each do |billboard| %>
		<li>
		<%= link_to billboard.name, billboard %>
		</li>
	<% end %>
</ul>

app/views/billboards/new.html.erb
<h1><%= @billboard.name %></h1>
<hr />

<h2><%= link_to "Add a Artist", new_billboard_artist_path(@billboard) %></h2>

app/views/billboards/show.html.erb
<h1><%= @billboard.name %></h1>
<%= link_to 'View Artists', billboard_artists_path(@billboard) %>
<br />
<%= link_to 'Edit', edit_billboard_path(@billboard) %>
<br />
<%= link_to 'Delete', @billboard, method: :delete %>
<br />
<p><%= link_to 'Top Billboards Home', root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard100</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<h1><%= @song.id ? 'Edit song' : 'Add song' %></h1>
<%= form_for [@artist, @song] do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, required: true %>
	<br />
	<%= f.label :genre %>
	<%= f.text_field :genre, required: true %>
	<br />
	<%= f.label :lenth %>
	<%= f.text_field :length, required: true %>
	<br />
	<%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1><%= @artist.name %> Songs</h1>
<%= link_to 'Add Song', new_artist_song_path(@artist) %>
<ul>
	<% @songs.each do |song| %>
		<li>
			<%= link_to song.name, [@artist, song] %>
		</li>
	<% end %>
</ul>
<%= link_to "Back to #{@artist.name}", billboard_artist_path(@artist.billboard_id,@artist) %>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1><%= @song.name %></h1>
<h3>Genre: <%= @song.genre %></h3>
<h3>Song Length: <%= @song.length %></h3>
<%= link_to 'Edit Song', edit_artist_song_path(@artist) %>
<br />
<%= link_to 'Delete', [@artist, @song], method: :delete %>
<p><%= link_to "Back to #{@artist.name} song list", artist_songs_path(@artist) %></p>